### ISSUE TITLE
Error with RedBean?

### ISSUE THREAD

**Issue by ghost** [ikoniaris/kippo-graph#23]
I did a pull-request yesterday and since then i get an error: PHP Fatal error:  Declaration of RedBeanPHP\\OODBBean::offsetGet() must be compatible with that of ArrayAccess::offsetGet(). Did the merge of the RedBean-branch gone wrong? I am working on CentOS 6.5 with PHP5.5.

All my other PHP-scripts work (also with MySQL).

**Comment by tofeeq** [comment]
Find 
public function & offsetGet( $offset )
and remove &
so it looks like 
public function offsetGet( $offset )
