### ISSUE TITLE
Big qty of scans

### ISSUE THREAD

**Issue by phantom-net** [ikoniaris/kippo-graph#24]
![problem](https://cloud.githubusercontent.com/assets/7779105/4782757/c35b35a0-5d04-11e4-9d9d-23d2645dcf6d.jpg)

Just a few lines are displayed in bottom table with thet amout of attempts.

**Comment by ikoniaris** [comment]
Hi @phantom-net, actually what you're seeing in not wrong. The upper table counts the opened sessions, while the 2nd table counts all login attempts. Unless if you mean something else? I noticed that you're missing the back/forward buttons for the second table but I'm not sure why. Chrome and Firefox show them correctly for me (with 1.4.1). Please `git pull` and let me know!
