### ISSUE TITLE
Google map and graph API changed

### ISSUE THREAD

**Issue by wirehack7** [ikoniaris/kippo-graph#29]
The heat map and Googlemaps map are not working properly anymore due the API changes of Google.

**Comment by ikoniaris** [comment]
@wirehack7 I'm not seeing any problems with the maps. Can you check again with the new 1.4?

**Comment by wirehack7** [comment]
No, it wont work anymore: ```Error validating selected GEO_METHOD.```

**Comment by wirehack7** [comment]
Oh, forget it. My fault, had to add the new *config.php*.
