### ISSUE TITLE
kippo not generating graph, even with chmod 777 on generated-graph

### ISSUE THREAD

**Issue by dummys** [ikoniaris/kippo-graph#30]
Hi, I use gentoo and no graph is generated.
I get xxxxx/generated-graphs/human_activity_per_week.png" failed (2: No such file or directory)
any Idea ?
It's on gentoo and php-fpm with nginx, pdo,mysql_pdo,gd is on
After enabling the error on php in your page i got this:

2015/01/20 11:42:31 [error] 22671#0: *346 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function imageftbbox() in xxx/include/libchart/classes/view/text/Text.php on line 74" while reading response header from upstream, client:, request: "GET xxx/kippo-graph.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: ", referrer: "lol"

Ok I figured that by myself, when you use this libchart library, you need to have php GD > 2.0 and php compiled with the freetype options.
On gentoo to have that, you need to add the "truetype" use flags to php.

I don't know if it's the same on other distro.
Problem solved !

**Comment by ikoniaris** [comment]
Thanks @dummys!
