### ISSUE TITLE
geo ip not localize

### ISSUE THREAD

**Issue by andreaconsadori** [ikoniaris/kippo-graph#31]
Why this ip are not correctly show on map?
103.41.124.xx

![kippo](https://cloud.githubusercontent.com/assets/1265395/5997217/8a891920-aab8-11e4-8a26-2900399afc95.JPG)

**Comment by ikoniaris** [comment]
Hi @andreaconsadori, which version are you using? What do you have as GEO_METHOD in config.php?

**Comment by andreaconsadori** [comment]
Version 1.4.2
define('GEO_METHOD', 'GEOPLUGIN');

**Comment by ikoniaris** [comment]
@andreaconsadori, what happens if you change it to 'LOCAL'?

**Comment by andreaconsadori** [comment]
with local it works as expected

**Comment by ikoniaris** [comment]
@andreaconsadori, my testbed works with both geo methods. It seems that geoplugin can't geolocate 103.41.124.XXX, (you can verify this online: http://www.geoplugin.com/), while MaxMind can. But for other IPs it works fine.
