### ISSUE TITLE
RedBeanPHP in Kippo Graph version 1.5 malfunctions

### ISSUE THREAD

**Issue by gkroon** [ikoniaris/kippo-graph#33]
Version 1.5 throws the following error at me after the first connection is made to Kippo (see attachment). I'm running FreeBSD 10.1p5, using MySQL 5.6.22 and PHP 5.4.37 from the repositories using pkg.

Fatal error: Uncaught [22001] - SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'country' at row 1 trace: #0 /usr/local/www/apache24/data/kippo-graph/include/rb.php(848): RedBeanPHP\Driver\RPDO->runQuery('INSERT INTO tem...', Array) #1 /usr/local/www/apache24/data/kippo-graph/include/rb.php(3024): RedBeanPHP\Driver\RPDO->Execute('INSERT INTO tem...', Array) #2 /usr/local/www/apache24/data/kippo-graph/include/rb.php(9305): RedBeanPHP\Adapter\DBAdapter->exec('INSERT INTO tem...', Array) #3 /usr/local/www/apache24/data/kippo-graph/include/rb.php(9922): RedBeanPHP\Facade::query('exec', 'INSERT INTO tem...', Array) #4 /usr/local/www/apache24/data/kippo-graph/class/KippoGeo.class.php(183): RedBeanPHP\Facade::exec('INSERT INTO tem...') #5 /usr/local/www/apache24/data/kippo-graph/kippo-geo.php(61): KippoGeo->printKippoGeoData()
![original](https://cloud.githubusercontent.com/assets/8877690/6200346/c0d3bf70-b473-11e4-96a2-6cca4ef142fa.jpg)
 #6 {main} thrown in /usr/local/www/apache24/data/kippo-graph/include/rb.php on line 636

**Comment by ikoniaris** [comment]
Hi @gkroon, this is happening due to this limit placed on the column length: https://github.com/ikoniaris/kippo-graph/blob/master/class/KippoGeo.class.php#L121 -- although, I'm expecting two letter country codes :confused:

**Comment by ikoniaris** [comment]
Aha, I think I know where the issue is. Probably one of your IPs couldn't be located and country code has a default "N/A" value: https://github.com/ikoniaris/kippo-graph/blob/master/class/KippoGeo.class.php#L14 which is 3 characters long. 

I've updated the code, can you `git pull` and try again?

**Comment by gkroon** [comment]
Awesome, it works! Yes, that's true, I used a private address, which is why it couldn't pinpoint my location. Nice fix, thanks. :)
![original](https://cloud.githubusercontent.com/assets/8877690/6200724/16847ae8-b485-11e4-8c40-9e739e08df74.jpg)
