### ISSUE TITLE
PHP 5.4 feature used in class/KippoGraph.class.php

### ISSUE THREAD

**Issue by honigbij** [ikoniaris/kippo-graph#34]
The following code in class/KippoGraph.class.php doesn't work in PHP < 5.4:

```
public function generatedKippoGraphChartsExist()
    {
        $generated_graphs_path = DIR_ROOT . '/generated-graphs/';
        $generated_graphs_names_array = [
            'top10_passwords.png',
```

 $generated_graphs_names_array = array ( ...) should be used instead of the new bracket construct.

**Comment by ikoniaris** [comment]
Thanks for suggestion @honigbij. This was fixed in d490f0704a4ade7f24e37ee2c9f0eaf04973aa06.
