### ISSUE TITLE
XSS Injection

### ISSUE THREAD

**Issue by Starow** [ikoniaris/kippo-graph#35]
Injection possible by an attacker logged into the honeypot kippo.
Location: 
1. `/kippo-graph/kippo-input.php` (The wget table at the bottom of the page.)
2. `/kippo-graph/kippo-playlog.php` (If cliking on the button "Play" to play the log)

An attacker can issue this command: `wget <script>alert()</script>` inside the kippo's console
and pown the viewer of the stat...

**Comment by ikoniaris** [comment]
@Starow thank you Jules. Question: which version of Kippo-Graph are you using?

**Comment by Starow** [comment]
On the home page it's written version 1.5

**Comment by ikoniaris** [comment]
This was fixed in commit: e6587ec598902763110b70c8bd0a72f7951b4997
