### ISSUE TITLE
Unable to generate graphs on fresh install

### ISSUE THREAD

**Issue by metac0rtex** [ikoniaris/kippo-graph#38]
It seems like I am unable to generate graphs on a fresh install of kippo-graph. I am getting the following errors on my web server error logs. 

2015/05/12 19:41:37 [error] 825#0: *56 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function imagecreatetruecolor() in /var/www/kippo-graph/include/libchart/classes/view/plot/Plot.php on line 253" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /kippo-input.php HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/kippo-graph.php"

I am running the latest pull from github.

**Comment by furiel** [comment]
I have run this problem too. If I rememer correctly, installing the gd library for php solved this one.
In case of ubuntu:
sudo apt-get install php5-gd
and an apache restart.

**Comment by metac0rtex** [comment]
Looks like that did it.

Thanks!

**Comment by ikoniaris** [comment]
@furiel, thanks for helping @metac0rtex :+1:
