### ISSUE TITLE
Error, permission denied in

### ISSUE THREAD

**Issue by MeiRos** [ikoniaris/kippo-graph#45]
Every time I go to the kippo-ip page, a new line appears in the apache error.log. It doesn't matter, if I have TOR check on or off. 
[:error] [pid 27914] [client my-ip:59436] PHP Warning:  file_put_contents(/var/www/html/kippo-graph/includ/tor/tor_exit_node_list.txt): failed to open stream: Permission denied in /var/www/html/kippo-graph/include/tor/tor.class.php on line 11, referer: http
://server-ip:8088/kippo-graph/kippo-ip.php

Is the TOR check failing?

**Comment by ikoniaris** [comment]
Hm.. It seems like the code doesn't have write access to the directory. Can you `chmod 777 /var/www/html/kippo-graph/include/tor/` and try again?

**Comment by MeiRos** [comment]
Thank You for the help!
Looks like tor exit node list needed chmod 776.
Is it ok to leave 776?

BTW
 I'm using ubuntu 14.04.4.

**Comment by ikoniaris** [comment]
Seems fine to me.
