### ISSUE TITLE
Fatal error: Class PDO not found in rb.php on line 743

### ISSUE THREAD

**Issue by CanadianJeff** [ikoniaris/kippo-graph#47]
```Fatal error: Class 'PDO' not found in /var/www/apache/kippo-graph/include/rb.php on line 743```

**Comment by CanadianJeff** [comment]
closing because its my own fault for not having PDO support enabled on my PHP rebuilding will probley fix this if it does not I will reopen.

**Comment by ikoniaris** [comment]
HI @CanadianJeff, I think the `php5-mysql` package will install the PDO driver. You might also need to enable the extension in your `php.ini` file.

**Comment by CanadianJeff** [comment]
thanks for the feedback suggestions I am using CentOS as my distro rebuilding php enabled PDO just fine for me and its working now
