### ISSUE TITLE
Reset stats on Kippo Graph

### ISSUE THREAD

**Issue by Nacnud01** [ikoniaris/kippo-graph#53]
Hi
First of all, thanks for a great product. I have been testing this for a few months now and I love the data you get back. I decided to clean up and reset the database. which went okay, but when I go on to the kippo graph web page on my honey pot it is still displaying old stats, logins and the like. How can I reset this data to show nothing?

Thanks for your help

Regards
Duncan

**Comment by ikoniaris** [comment]
Hi @Nacnud01, thanks for your message. Hm, what do you mean old data is showing? Kippo-Graph just hits the database to get the data. Unless your DB is empty or something in which case the old images might be displayed. I suggest you go to kippo-graph/generated-graphs folder and delete all images. Then try again. Also hard refresh your browser just in case.

**Comment by Nacnud01** [comment]
Hi Ikoniaris
Thanks for the reply, I can see that now :O) I emptied the database then went into kippoGraph and noticed it was still showing the old stats. What I should have done was to run it and give it time to refresh, then I would have seen, as you rightly pointed out, it reflecting the newly created database and shows them all new again :O)

Thanks very much for taking the time to answer my question.

Kind Regards
Nacnud01
