### ISSUE TITLE
Can't open my kippo-graph page

### ISSUE THREAD

**Issue by artoev95** [ikoniaris/kippo-graph#60]
I have set up the kippo-graph in my machine but I can't seem to access the page ,the page simply won't load . Here are some screenshots of what I'm trying to do :

Here are details of my machine
![snip](https://cloud.githubusercontent.com/assets/17414819/22563052/f66c8ec0-e976-11e6-8e01-cfa99af80b29.JPG)

![kippo](https://cloud.githubusercontent.com/assets/17414819/22563068/09cabae6-e977-11e6-9bf1-a1ebdb2df54f.JPG)

The highlighted area is where the kippo-graph is saved

**Comment by ikoniaris** [comment]
Well, it looks like you're not running a web server. Please read this again: https://github.com/ikoniaris/kippo-graph#requirements
