### ISSUE TITLE
Kippo-graph work with latest PHP and Mysql? Missing graphs!

### ISSUE THREAD

**Issue by biggen1684** [ikoniaris/kippo-graph#62]
I'm getting apache errors with my new Kippo-Graph installation.  I'm running Cowrie as the honeypot.  I'm only getting some graphs generated and others are missing. Yes, I have made sure that /var/www/html/kippo-graph/generated-graphs was chmod to 777. 

In particular, Kippo-graph is only generating the following graphs: Top10 passwords attempted, Top 10 usernames attempted, Top 10 username/password combinations (in both pie and bar chart), Overall success ratio, Number of connections per country, Number of connections per unique IP (in both pie and bar chart), and finally Top 10 successful username/password combinations (in both pie and bar chart).  I'm missing the rest of the graphs and the overview page is totally empty.

Here is a snippet of some of the errors from my apache log:
`[Tue Mar 14 17:39:17.257562 2017] [:error] [pid 5514] [client 192.168.22.153:51759] PHP Warning:  imagepng(/var/www/html/kippograph/generated-graphs/top10_passwords.png): failed to open
stream: Permission denied in /var/www/html/kippograph/include/libchart/classes/view/plot/Plot.php on line 295, referer: http://10.0.0.2/kippograph/`

`[Tue Mar 14 17:39:17.413266 2017] [:error] [pid 5514] [client 192.168.22.153:51759] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expressio
n #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cowrie.auth.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompa
tible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/kippograph/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(se...', Array)\n#1 /var/www/html/kippogra
ph/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(se...', Array)\n#2 /var/www/html/kippograph/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUN
T(se...', Array)\n#3 /var/www/html/kippograph/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(se...', Array)\n#4 /var/www/html/kippograph/class/KippoGraph.class.php(
253): RedBeanPHP\\Facade::getAll('SELECT COUNT(se...')\n#5 /var/www/html/kippograph/class/KippoGraph.class.php(26): KippoGraph->createMostSuccessfulLoginsPerDay()\n#6 /var/www/html/kippo
graph/kippo-graph.php(62) in /var/www/html/kippograph/include/rb.php on line 636, referer: http://10.0.0.2/kippograph/`

The install instructions listed at https://bruteforce.gr/kippo-graph don't really pertain to Ubuntu 16 server.  You can't install PHP5 packages like that anymore with Ubuntu 16.  

If you want to install the newest packages you have to drop all the "5"'s from that apt-get install command.  Do I need to specifically install PHP5 and not the default PHP with I think is version 7 now?

**Comment by biggen1684** [comment]
I ended up giving up and going with Debian 8 which works now with Kippo-Graph.

Kippo-Graph doesn't seem to work 100% with Ubuntu 16.  I think it's because there must be some incompatibility with either the newer PHP or Mysql versions and Kippo-Graph.  I don't have the time nor knowledge to fully figure it out.  Maybe this will help someone in the future and perhaps Kippo-Graph will be updated to work with Ubuntu 16 as well.

**Comment by ikoniaris** [comment]
Thanks for the update @biggen1684, I'll try to take a look when I have time (hopefully "soon").

**Comment by maxitis92** [comment]
I have the below problem.

Not generate graphs. 

I have made that /var/www/html/kippo-graph/generated-graphs was chmod to 777.


tail -f /var/log/apache2/error.log

[Fri Sep 21 21:46:39 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:39 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_failed_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:39 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:39 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_passwords.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_usernames.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_combinations.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_combinations_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/success_ratio.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/most_successful_logins_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/successes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/successes_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/logins_from_same_ip.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/most_probes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/probes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/probes_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_ssh_clients.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_country_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_geo.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_geo_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_busiest_days.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_overall_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_failed_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:47 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_passwords.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_usernames.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_combinations.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_combinations_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/success_ratio.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/most_successful_logins_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/successes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/successes_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/logins_from_same_ip.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/most_probes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/probes_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/probes_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_ssh_clients.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_country_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_geo.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/connections_per_ip_geo_pie.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_busiest_days.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_per_day.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/human_activity_per_week.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_overall_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_failed_input.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations.png, referer: http://localhost/kippo-graph/gallery.php
[Fri Sep 21 21:46:49 2018] [error] [client 127.0.0.1] File does not exist: /var/www/kippo-graph/generated-graphs/top10_successful_combinations_pie.png, referer: http://localhost/kippo-graph/gallery.php



Can you help me anyone?
Thank you
